[package]
name = "nats_client"
version = "0.1.0"
authors = ["Brian Shannan <brianshannan@gmail.com>"]

[dependencies]
log = "0.3"
rand = "*"
rustc-serialize = "0.3"
url = "1.1.0"

[dependencies.openssl]
version = "0.7.12"
features = ["tlsv1_2"]
